### ISSUE TITLE
Failed with Termsig=11 if string's length less then 8 

### ISSUE THREAD

**Issue by maxmacc** [sjinks/php-stribog#1]
I'm trying to use it on CentOS 7 with PHP 7.2.10 and seems like it cannont work with input strings with length < 8.
[hash_string.log](https://github.com/sjinks/php-stribog/files/2405109/hash_string.log)

[hash_string.phpt.txt](https://github.com/sjinks/php-stribog/files/2405110/hash_string.phpt.txt)

**Comment by sjinks** [comment]
Fixed in 00e70a5, thank you!
