### ISSUE TITLE
Could it be as a function in single php file?

### ISSUE THREAD

**Issue by djdance** [sjinks/php-stribog#10]
One more question, please.
Is it possible to have your Stribog algo as a single function in one .php file? Without having to install hash extensions and w/o dependency of environment. No matter how slow this realisation will be. Just all math in one script.

**Comment by sjinks** [comment]
Probably not… In PHP, the math is signed; this can affect the logical operations.

For example, in PHP, `0xFFFFFFFFFFFFFFFF ^ 0x01 === 1`. In C, `0xFFFFFFFFFFFFFFFF ^ 0x01 == 0xFFFFFFFFFFFFFFFE`.
