### ISSUE TITLE
no extension appeared

### ISSUE THREAD

**Issue by djdance** [sjinks/php-stribog#8]
I made it all without errors

```
phpize
./configure
make
sudo make install
```

it has said, in particular:

> Libraries have been installed in:
>    /var/www/project/php-stribog/modules
> .....
> Installing shared extensions:     /usr/lib/php/20180731/
> .....
> If you ever happen to want to link against installed libraries
> in a given directory, LIBDIR, you must either use libtool, and
> specify the full pathname of the library, or use the '-LLIBDIR'
> flag during linking and do at least one of the following....

but no "stribog" appeared in hash_algos().

Should I restart server, remake php, use libtool/LIBDIR as mentioned above or do something else? Thanks

**Comment by sjinks** [comment]
Hello,

You probably need to add

```
extension=stribog.so
```

to your php.ini

**Comment by djdance** [comment]
added, restarted, nothing changed
Maybe I have to add path /usr/lib/php/20180731/ to somewhere?

**Comment by sjinks** [comment]
Does

```bash
php -i | grep extension_dir
```

show the correct directory?

**Comment by djdance** [comment]
apparently, yes

> extension_dir => /usr/lib/php/20180731 => /usr/lib/php/20180731
> sqlite3.extension_dir => no value => no value
> 

if it helps:
- if we run your tests being inside var/www/project/php-stribog/ , they are all successfully passed.
- if we open our script **project/php-stribog/test.php** from browser, it fails.
`<?php extension_loaded('stribog') ?>`

Maybe need to build and install php-stribog globally? not in a project?

**Comment by sjinks** [comment]
You need to restart Apache after you modify php.ini

**Comment by djdance** [comment]
both were restarted, sure ...

**Comment by sjinks** [comment]
OK, if you run `phpinfo()` from the browser, there should be the rows like "Configuration File (php.ini) Path" and "Additional .ini files parsed". Is there a file where you have put `extension=stribog.so`, in the list?

**Comment by djdance** [comment]
you're quite right! it was wrong php.ini (fpm vs particular php version/apache)
thank you.
